### ISSUE TITLE
Print individual label button prints all people

### ISSUE THREAD

**Issue by garrettjohnson** [NewSpring/rock-attended-checkin#23]
When attempting to print one person on the confirmation page, checkin will print all people listed on the confirmation screen. (All print behavior matches the print all button)

Our check-in type is currently set as individual rather than family.

**Comment by dcs619** [comment]
@garrettjohnson Are you up to date on the code?  We noticed that problem last week and was fixed [here](https://github.com/NewSpring/rock-attended-checkin/commit/ca799654e9d36eb0c046a739320e88b3d49b84ee).  I'll leave this issue open until you confirm.

**Comment by garrettjohnson** [comment]
Fixed! Thanks
